repos:
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.45.0
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --no-summary, src/]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.7
    hooks:
      - id: uv-lock
      - id: uv-export

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.97.1
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog filesystem . --only-verified --fail'
        language: system
        stages: ["pre-commit"]

  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.11
    hooks:
      - id: ripsecrets

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.4.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            refactor,
            chore,
            build,
            ci,
            docs,
            feat,
            fix,
            test,
            perf,
            style,
            BREAKING_CHANGE,
          ]

  - repo: https://github.com/timmyb824/sops-file-encryption-check
    rev: latest
    hooks:
      - id: sops-encryption-check
